# Replicating Calvano et al. (2020)
## Baseline
### Author: Andréa Epivent

In [1]:
# Set working directory
import os
path = os.getcwd()

# Import packages
exec(open(path+"/packages.py").read())

# Import custom functions
from functions import *

# Import parameters
exec(open(path+"/parameters.py").read())

In [2]:
# Create output folders
try: 
    os.mkdir("Output")
    os.mkdir("Output/Baseline")
    print("Directories are created")
except:
    print("Directories already exist")

Directories already exist


### Initialization

* Action space

In [3]:
# m equally spaced points in an interval that includes Nash and monopoly prices
A = np.linspace(p_N()-ksi*(p_M()-p_N()),p_M()+ksi*(p_M()-p_N()),m)
print(A.shape)
print(A)

(15,)
[1.42772123 1.46646874 1.50521625 1.54396376 1.58271127 1.62145877
 1.66020628 1.69895379 1.7377013  1.77644881 1.81519631 1.85394382
 1.89269133 1.93143884 1.97018634]


* State space

In [4]:
# Combination of prices from last period
S = np.zeros([state_space, 2])
l = 0
for i in A: # price of agent 1
    for j in A: # price of agent 2
        S[l,0] = i
        S[l,1] = j
        l += 1
print(S.shape)

(225, 2)


In [5]:
np.save(path+'/Output/Baseline/actions', A)
np.save(path+'/Output/Baseline/states', S)

* Initialize Q-matrix

In [6]:
q_table = init_Q(A)
print(q_table)

[[5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]
 [5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]
 [5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]
 ...
 [5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]
 [5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]
 [5.7897605  6.00810841 6.16208425 ... 4.74351758 4.42959923 4.11117874]]


### Training

* Launch training

In [7]:
conv_info, q_tables1, q_tables2 = q_learning_2agents(S, A, q_table, save_info=False)

Iteration: 1913700
Episode: 999
Process has converged
Training finished, episode: 999
--- 4251.674920860926 minutes ---


* Store results

In [10]:
# Information on prices and profits throughout simulation for both agents
try:
    np.save(path+'/Output/Baseline/q_info', q_info)
except:
    pass

# Number of iterations per episode
np.save(path+'/Output/Baseline/conv_info', conv_info)

# Last Q matrix of both agents
np.save(path+'/Output/Baseline/q_table_a1', q_tables1)
np.save(path+'/Output/Baseline/q_table_a2', q_tables2)